"""Update Country model

Revision ID: 5e33fbf9ae7c
Revises: a82b8a239dc0
Create Date: 2020-04-14 00:59:08.691586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e33fbf9ae7c'
down_revision = 'a82b8a239dc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('country', 'code')
    # ### end Alembic commands ###
